#!/bin/sh

im $OWNER || Forbidden

if test $REQUEST_METHOD = POST; then
	fd type > type
	fd data > data.txt
	fd yt > yt
	reindex chords $iid
	SeeOther ../
fi

cat <<!
<form action='.' method='POST' class='p sf f v' enctype='multipart/form-data'>
<textarea name='data' style='height: 60vh; white-space: pre;'>
`cat data.txt`
</textarea>

<textarea name='type' style='height: 13vh; white-space: pre;'>
`cat type`
</textarea>

<label>YouTube
<input name='yt' value="`cat yt`"></input>
</label>

<button>`_ Submit`</button>
!
