#!/bin/sh

test ! -z "$HTTP_PARAM_t" || HTTP_PARAM_t=0

test -z "$HTTP_PARAM_r" || flags="$flags -B"

_TITLE="`cat title`"

if is_main; then
	im $OWNER || buttons="$buttons`IFB "🔱" "fork" "$DOCUMENT_URI/fork"`"
else
	buttons="$buttons`RB "🔍" "" "$DOCUMENT_URI/diff"`"
	im $ORIG_OWNER && buttons="$buttons`IFB "🟣" "$DOCUMENT_URI/merge"`"
fi

invert_chords=1
. ../../lib

key_form() {
	key_select data.txt $HTTP_PARAM_t \
		| FB "🎚️" "tune" "" "GET" "t"
}

test ! -z "$HTTP_PARAM_c" || buttons="$buttons`key_form`"

echo "$buttons" >> $DOCUMENT_ROOT/tmp/fun

chords_print $iid $HTTP_PARAM_t "`cat type`"

cat - <<!
<div id="osmdContainer" class="shf"></div>
<script src="https://unpkg.com/opensheetmusicdisplay@1.9.0/build/opensheetmusicdisplay.min.js"></script>
<script>
  var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdContainer");
  osmd.TransposeCalculator = new opensheetmusicdisplay.TransposeCalculator();
  osmd.setOptions({
    backend: "canvas",
    drawTitle: false,
    drawingParameters: "compact"
  });
  osmd
    .load("https://tty.pt/$iid.musicxml")
    .then(
      function() {
        osmd.Zoom = 0.7;
        osmd.Sheet.Transpose = +$HTTP_PARAM_t;
	osmd.updateGraphic();
        osmd.render();
      }
    );
</script>
!
