#!/bin/sh

chords_path="$DOCUMENT_ROOT/items/chords/items/"
transp="$chords_path../src/transp/bin/transp"

show_video() {
	local yt="`zcat $1`"
	test -z "$yt" || \
		printf "\n<div><iframe src='https://www.youtube.com/embed/$yt' frameborder='0'></iframe></div>"
}

ignore() {
}

show_video=ignore
TB v ▶️  "video" ⏸️ "no video" || show_video=show_video

if TB c 🎸 "chords" 🎤 "lyrics" $invert_chords; then
	flags="$flags -C"
	nc=1
else
	TB l 🏛️ "latin" 🔠 "caged" || flags="$flags -l"
	TB b 🅱️ "bemol" "#️⃣" "sustain"  || flags="$flags -b"
fi

zoomv="`zcat $DOCUMENT_ROOT/home/$REMOTE_USER/.tty/chords-zoom || echo 0.9`"

zoom() {
	cat <<!
<label>
	<div>`__ zoom`</div>
	<input type="range" min="0.8" max="1.6" step="0.05" value="$zoomv" onchange="zoom(this.value)"></input>
<script>
let main = null;
function zoom(value) {
	main.style.fontSize = "calc(" + value + " * 0.8rem)";
	fetch("/chords/zoom?v=" + encodeURIComponent(value));
}
document.addEventListener("DOMContentLoaded", () => {
	main = document.getElementById("main");
	console.log("Loaded", $zoomv);
	main.style.fontSize = "calc($zoomv * 0.8rem)";
});
</script>
</label>
!
}

buttons="$buttons`zoom`"

key_options() {
	cat $1 | $transp $flags -s | while read name tra; do
		test "$tra" = "$2" && attr="selected" || attr=""
		echo "<option $attr value='$tra'>$name</option>"
	done
}

key_select() {
	local name="$3"
	local onchange=""
	test ! -z "$4" || onchange="onchange='this.form.submit()'"
	test ! -z "$name" || name="t"
	echo "<select name='$name' $onchange>"
	key_options $1 $2
	echo "</select>"
}

shift_chords() {
}

# chords_path should be set,
# flags and counter can be set too
# alongside show_video
chords_print() {
	song=$1
	t=$2
	fmt=$3
	link="`echo $song | awk '{print $1}'`"
	song_dir="$chords_path/$link"
	path="$song_dir/data.txt"
	lypath="$song_dir/data.ly"
	test -f "$lypath" \
		&& lyink="<a href='/chords/$link/data.ly'>𝄞</a> " \
		|| lyink=

	type="<h6>$fmt</h6>"

	echo "<div class='v8 f'>"
	cat - <<!
<span id='$counter' class='h f fic'>
<div class="v0 f fg">
<h4>$lyink<a href='/chords/$link/'>`cat $chords_path/$link/title`</a></h4>
$type
</div>
`shift_chords $counter $t $song_dir`
</span>
`$show_video $song_dir/yt`
!
	echo "<pre lang='pt'>"
	cat "$path" | $transp -h $flags -t $t
	echo "</pre></div>"
}
