#!/bin/sh
link=$1
$qdb -d"$link" ../assoc.db > /dev/null
cat type | while read type; do
	test ! -z "$type" || continue
	typeid="`echo $type | translate`"
	echo "-p\"$link:$typeid\""
done | xargs -I {} $qdb {} ../assoc.db > /dev/null
